### ISSUE TITLE
Question about whitespace

### ISSUE THREAD

**Issue by kaelig** [Shopify/tslint-config-shopify#73]
The new config seems to promote `import { foo } from 'foo'`, whereas old versions seemed to promote  `import {foo} from 'foo'`. Is this change intended?

I'd be for the additional whitespace, since that's something that prettier would work well with.

(Note: I discovered this change as well as other config changes when upgrading TSLint in https://github.com/Shopify/polaris-styleguide/pull/903)

**Comment by GoodForOneFare** [comment]
The styleguide mandates no spaces: https://github.com/Shopify/javascript#4.9

I'd be against changing this because it would touch thousands of files with no clear benefit (fwiw, when the eslint rule for this was added, I argued for more whitespace because it was closer to our Ruby style).

PRs to update the rules are welcome 😄 If nobody has time, @ismail-syed will get to it when he has the bandwidth.

**Comment by kaelig** [comment]
Thank you for the feedback! I opened a PR for a fix.
